# Generated by Django 5.1.7 on 2025-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentprofile',
            name='medication_schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
