# Generated by Django 5.1.7 on 2025-03-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_residentprofile_medication_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='reminder_message',
            field=models.TextField(default='Take the medicine'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
